Update to GraalVM 23 with new URL style

diff --git a/env-setup b/env-setup
--- a/env-setup
+++ b/env-setup
@@ -6,33 +6,43 @@ graal_arch="$(uname -m)"
 # Override graal_arch when on amd64
 if [[ "$graal_arch" == "x86_64" ]] || [[ "$graal_arch" == "x64" ]]
 then
-  graal_arch="amd64"
+  graal_arch="x64"
 fi
 
-graal_ver="22.3.0"
-graal_os="$( uname -s | tr "[:upper:]" "[:lower:]")"
-graal_ar="graalvm-ce-java11-${graal_os}-${graal_arch}-${graal_ver}.tar.gz"
-graal_dir="$(pwd)/graalvm-ce-java11-${graal_ver}"
-graal_url="https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-${graal_ver}/${graal_ar}"
 
-# Start fresh
-if [ -d "${graal_dir}" ]
+graal_ver="23.0.2"
+graal_os="$( uname -s | tr "[:upper:]" "[:lower:]")"
+graal_ar="graalvm-community-jdk-${graal_ver}_${graal_os}-${graal_arch}_bin.tar.gz"
+graal_dir_prefix="$(pwd)/graalvm-community-openjdk-${graal_ver}"
+graal_url="https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${graal_ver}/${graal_ar}"
+
+# Start fresh removing all prefixed directories
+if [ -d "${graal_dir_prefix}"* ]
 then
-   rm -r "${graal_dir}"
+   rm -r "${graal_dir_prefix}"*
 fi
 
 
 # Download Graal
+echo "[INFO] Downloading GraalVM from: ${graal_url}"
 curl -L "${graal_url}" | tar -xz
+graal_dir="`ls -d ${graal_dir_prefix}* | head -1`"
+
+echo "[INFO] Inferring GraalVM Home as: ${graal_dir}"
 graal_bin="${graal_dir}/bin"
 if [ ! -d "${graal_bin}" ]
 then
     graal_bin="${graal_dir}/Contents/Home/bin"
 fi
+# Check directory detection
+if [ ! -d "${graal_bin}" ]
+then
+   echo "[ERROR] Failed to find GraalVM bin dir!"
+   exit 1
+fi
+
 export PATH="${graal_bin}:${PATH}"
 export GRAALVM_JAVA_HOME="$(dirname ${graal_bin})"
-# Install native image
-${graal_bin}/gu install native-image
 
 if [ -n "$GITHUB_ENV" ]
 then
